# Generated by Django 3.2.5 on 2021-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210803_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
