# Generated by Django 3.2 on 2021-04-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210425_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
