# Generated by Django 3.2 on 2021-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_photo',
            field=models.ImageField(upload_to='profile_photo'),
        ),
    ]
