# Generated by Django 3.2 on 2021-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_avatar_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_photo',
            field=models.ImageField(default='static/assets/images/default_avatar.jpg', upload_to='profile_photo'),
        ),
    ]
